language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

git:
  depth: 3

install:
  - go get -v github.com/kardianos/govendor
  - govendor sync
  - go get -u github.com/campoy/embedmd
  - go get -u github.com/gin-gonic/gin


script:
  - embedmd -d README.md
  - go test -v -covermode=count -coverprofile=coverage.out